spring.application.name=supplier-order-manager
spring.datasource.url=jdbc:postgresql://localhost:5432/supplierOrderManager
# Credenciales ? definidas en application-local.properties
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false